"""erp procurement warehouse orders

Revision ID: bee5c25e3ca5
Revises: a6018d7b6512
Create Date: 2026-10-03 22:59:37.604353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee5c25e3ca5'
down_revision: Union[str, None] = 'a6018d7b6512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('warehouse_locations',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_locations_code'), 'warehouse_locations', ['code'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('po_no', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Double(), nullable=False),
    sa.Column('expected_date', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=True)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('stocktakings',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_items',
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Double(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_po_items_po', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('shipments',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracking_no', sa.String(length=64), nullable=True),
    sa.Column('carrier', sa.String(length=32), nullable=True),
    sa.Column('shipped_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipments_order', 'shipments', ['order_id'], unique=False)
    op.create_table('stocktaking_items',
    sa.Column('stocktaking_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('system_qty', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stocktaking_id'], ['stocktakings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stocktaking_items_stocktaking', 'stocktaking_items', ['stocktaking_id'], unique=False)
    op.create_table('batches',
    sa.Column('batch_no', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('po_item_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('qty_initial', sa.Integer(), nullable=False),
    sa.Column('qty_remaining', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_batch_no'), 'batches', ['batch_no'], unique=True)
    op.create_index('ix_batches_product', 'batches', ['product_id'], unique=False)
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_items_shipment', 'shipment_items', ['shipment_id'], unique=False)
    op.add_column('orders', sa.Column('platform', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('receiver_name', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('receiver_phone', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('receiver_address', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'receiver_address')
    op.drop_column('orders', 'receiver_phone')
    op.drop_column('orders', 'receiver_name')
    op.drop_column('orders', 'platform')
    op.drop_index('ix_shipment_items_shipment', table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index('ix_batches_product', table_name='batches')
    op.drop_index(op.f('ix_batches_batch_no'), table_name='batches')
    op.drop_table('batches')
    op.drop_index('ix_stocktaking_items_stocktaking', table_name='stocktaking_items')
    op.drop_table('stocktaking_items')
    op.drop_index('ix_shipments_order', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_po_items_po', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_table('stocktakings')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_warehouse_locations_code'), table_name='warehouse_locations')
    op.drop_table('warehouse_locations')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
